src/java/py/com/palermo/curriculolanacion/web/CurriculoBean.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package py.com.palermo.curriculolanacion.web;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;
import javax.ejb.EJB;

import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;

import javax.inject.Named;
import org.joda.time.LocalDate;
import org.joda.time.format.DateTimeFormat;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import py.com.palermo.curriculolanacion.entities.Area;
import py.com.palermo.curriculolanacion.entities.Curriculo;
import py.com.palermo.curriculolanacion.entities.EstadoCurriculo;
import py.com.palermo.curriculolanacion.entities.ExperienciaLaboral;
import py.com.palermo.curriculolanacion.entities.ReferenciaLaboral;
import py.com.palermo.curriculolanacion.entities.ReferenciaPersonal;
import py.com.palermo.curriculolanacion.generico.AbstractDAO;
import py.com.palermo.curriculolanacion.generico.BeanGenerico;
import py.com.palermo.curriculolanacion.sesionbeans.interfaces.IAreaDAO;
import py.com.palermo.curriculolanacion.sesionbeans.interfaces.ICurriculoDAO;
import py.com.palermo.curriculolanacion.sesionbeans.interfaces.IEmpresaDAO;

/**
 *
 * @author christian
 */
@Named
@ViewScoped
public class CurriculoBean extends BeanGenerico<Curriculo> implements Serializable {

    @EJB
    private ICurriculoDAO ejb;
    @EJB
    private IAreaDAO areaDAO;
    @EJB
    private IEmpresaDAO empresaDAO;

    private UploadedFile file;

    @Override
    public Curriculo getActual() {
        Curriculo R = super.getActual();
        if (R.getId() == null || R.getId() == 0) {

            if (R.getReferenciasLaborales() == null) {
                List<ReferenciaLaboral> refsLaboral = new ArrayList<>();
                ReferenciaLaboral rl1 = new ReferenciaLaboral();
                rl1.setIndice(1);
                rl1.setCurriculo(R);
                ReferenciaLaboral rl2 = new ReferenciaLaboral();
                rl2.setCurriculo(R);
                rl2.setIndice(2);

                refsLaboral.add(rl1);
                refsLaboral.add(rl2);
                R.setReferenciasLaborales(refsLaboral);
            }

            if (R.getReferenciasPersonales() == null) {
                List<ReferenciaPersonal> refsPersonales = new ArrayList<>();

                ReferenciaPersonal rp1 = new ReferenciaPersonal();
                ReferenciaPersonal rp2 = new ReferenciaPersonal();
                rp1.setCurriculo(R);
                rp2.setCurriculo(R);
                rp1.setIndice(1);
                rp2.setIndice(2);

                refsPersonales.add(rp1);
                refsPersonales.add(rp2);

                R.setReferenciasPersonales(refsPersonales);
            }

            if (R.getExperienciasLaborales() == null) {
                List<ExperienciaLaboral> expsLaborales = new ArrayList<>();
                ExperienciaLaboral exp1 = new ExperienciaLaboral();
                ExperienciaLaboral exp2 = new ExperienciaLaboral();
                exp1.setIndice(1);
                exp2.setIndice(2);
                exp1.setCurriculo(R);
                exp2.setCurriculo(R);

                expsLaborales.add(exp1);
                expsLaborales.add(exp2);

                R.setExperienciasLaborales(expsLaborales);
            }
        }

        return R;
    }

    @Override
    public AbstractDAO<Curriculo> getEjb() {
        return ejb;
    }

    @Override
    public Curriculo getNuevo() {
        return new Curriculo();
    }

    public UploadedFile getFile() {
        return file;
    }

    public void setFile(UploadedFile file) {
        this.file = file;
    }

    public SelectItem[] getSelectItemsAreas() {

        List<Area> listaAreas;
        if (getActual().getEmpresa() == null) {
            listaAreas = areaDAO.findAllSinEmpresa();

        } else if (empresaDAO.tieneArea(getActual().getEmpresa())) {
            listaAreas = areaDAO.findAllConEmpresa(getActual().getEmpresa());
        } else {
            listaAreas = areaDAO.findAllSinEmpresa();
        }

        SelectItem[] items = new SelectItem[listaAreas.size() + 1];
        int i = 0;
        items[0] = new SelectItem("", "Todas las areas");
        i++;
        for (Area a : listaAreas) {
            items[i++] = new SelectItem(a, a.toString());
        }

        return items;
    }

    public SelectItem[] getSelectItemsDias() {
        SelectItem[] items = new SelectItem[32];
        items[0] = new SelectItem("", "--");
        for (int i = 1; i < 32; i++) {
            items[i] = new SelectItem("" + i, "" + i);
        }
        return items;
    }

    public SelectItem[] getSelectItemsAnios() {
        SelectItem[] items = new SelectItem[41];
        items[0] = new SelectItem("", "--");
        for (int i = 1; i < 41; i++) {
            items[i] = new SelectItem("" + (i + 1959), "" + (i + 1959));
        }
        return items;
    }

    public SelectItem[] getSelectItemsMes() {
        SelectItem[] items = new SelectItem[13];
        items[0] = new SelectItem("", "--");
        items[1] = new SelectItem("01", "Enero");
        items[2] = new SelectItem("02", "Febrero");
        items[3] = new SelectItem("03", "Marzo");
        items[4] = new SelectItem("04", "Abril");
        items[5] = new SelectItem("05", "Mayo");
        items[6] = new SelectItem("06", "Junio");
        items[7] = new SelectItem("07", "Julio");
        items[8] = new SelectItem("08", "Agosto");
        items[9] = new SelectItem("09", "Septiembre");
        items[10] = new SelectItem("10", "Octubre");
        items[11] = new SelectItem("11", "Noviembre");
        items[12] = new SelectItem("12", "Diciembre");

        return items;
    }

    public void handleFileUpload(FileUploadEvent event) throws IOException {
        if (event.getFile() != null) {

            file = event.getFile();
            getActual().setAdjunto(file.getFileName());
            System.out.println("FILE: " + file);
        }
    }

    public void copyFile() {
        try {

            System.out.println("FILE en COPY: " + file);
            FacesContext fc = FacesContext.getCurrentInstance();
            String destination = fc.getExternalContext().getInitParameter("uploadDirectory");

            final String uuid = UUID.randomUUID().toString().replaceAll("-", "");
            destination += uuid;

            OutputStream out = new FileOutputStream(new File(destination + file.getFileName() + "." + (file.getFileName().split("\\."))[1]));

            System.out.println("DIR:  " + destination);
            int read = 0;
            byte[] bytes = new byte[1024];

            InputStream in = file.getInputstream();
            while ((read = in.read(bytes)) != -1) {
                out.write(bytes, 0, read);
            }

            in.close();
            out.flush();
            out.close();

            System.out.println("New file created!");

            getActual().setDirectoryUUID(uuid);

        } catch (IOException e) {
            getActual().setAdjunto(null);
            System.out.println(e.getMessage());
        }
    }

    public String guardar() {
        if (file != null) {
            copyFile();
        }

        LocalDate birthdate = LocalDate.parse(getActual().getAnioNac() + "-" + getActual().getMesNac() + "-" + getActual().getDiaNac(),
                DateTimeFormat.forPattern("yyyy-MM-dd"));
        getActual().setFechaNacimiento(birthdate.toDate());

        edit();
        return "/main/curriculo/listado";
    }

    public String guardar2() {
        if (file != null) {
            copyFile();
        }

        LocalDate birthdate = LocalDate.parse(getActual().getAnioNac() + "-" + getActual().getMesNac() + "-" + getActual().getDiaNac(),
                DateTimeFormat.forPattern("yyyy-MM-dd"));
        getActual().setFechaNacimiento(birthdate.toDate());

        edit();
        return "/confirmacion";
    }

    public String preseleccionar() {
        Long idActual = getActual().getId();
        getActual().setEstadoCurriculo(EstadoCurriculo.PRESELECCIONADO);
        getActual().setFechaSeleccionado(new Date());
        edit();
        return "vista.xhtml?faces-redirect=true&id=" + idActual;
    }

    public String contratar() {
        Long idActual = getActual().getId();
        getActual().setEstadoCurriculo(EstadoCurriculo.CONTRATADO);
        getActual().setFechaContratado(new Date());
        edit();
        return "vista.xhtml?faces-redirect=true&id=" + idActual;
    }

    public String pasarANuevo() {
        Long idActual = getActual().getId();
        getActual().setEstadoCurriculo(EstadoCurriculo.NUEVO);
        getActual().setFechaSeleccionado(null);
        getActual().setFechaContratado(null);
        edit();
        return "vista.xhtml?faces-redirect=true&id=" + idActual;
    }

    public Long getCountNuevos() {
        return ejb.countEstado(EstadoCurriculo.NUEVO);
    }

    public Long getCountPreseleccionado() {
        return ejb.countEstado(EstadoCurriculo.PRESELECCIONADO);
    }

    public Long getCountContratado() {
        return ejb.countEstado(EstadoCurriculo.CONTRATADO);
    }

}

web/WEB-INF/footer.xhtml
<ui:composition 

    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">




    <div id="layout-footer">
        <div id="layout-footer-indent">
            <a href="http://www.grupocartes.com.py/" style="position: relative; left: 20px; top: 5px"><p:graphicImage library="img" name="logo.png" height="100"/></a>
        </div>
    </div>


</ui:composition>

web/WEB-INF/layoutmenu.xhtml
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pv="http://primefaces.org/volt">



    <h:form id="menuform">

        <pv:menu>

            <p:submenu label="Curriculum" icon="fa fa-user">
                <p:menuitem id="rm_main_curriculo_todos" value="Busqueda Avanzanda" icon="fa fa-search" outcome="/main/curriculo/listado" />
                <p:menuitem id="rm_main_curriculo_nuevo" value="Agregar Nuevo" icon="fa fa-plus" outcome="/main/curriculo/nuevo" />
            </p:submenu>


            <p:submenu label="Configuraciones" icon="fa fa-cog">
                <p:menuitem id="rm_admin_empresa" value="Empresa" icon="fa fa-cog" outcome="/admin/empresa/listado"/>
                <p:menuitem id="rm_admin_area" value="Área" icon="fa fa-cog" outcome="/admin/area/listado"/>
                <p:menuitem id="rm_admin_departamento" value="Departamento" icon="fa fa-cog" outcome="/admin/departamento/listado"/>
                <p:menuitem id="rm_admin_ciudad" value="Ciudad" icon="fa fa-cog" outcome="/admin/ciudad/listado"/>
                <p:menuitem id="rm_admin_estadocivil" value="Estado Civil" icon="fa fa-cog" outcome="/admin/estadoCivil/listado"/>
                <p:menuitem id="rm_admin_nacionalidad" value="Nacionalidad" icon="fa fa-cog" outcome="/admin/nacionalidad/listado"/>
                <p:menuitem id="rm_admin_nivel" value="Nivel Académico" icon="fa fa-cog" outcome="/admin/nivelAcademico/listado"/>
                <p:menuitem id="rm_admin_estadonivel" value="Estado Nivel Académico" icon="fa fa-cog" outcome="/admin/estadoNivelAcademico/listado"/>
                <p:menuitem id="rm_admin_tipodocumento" value="Tipo Documento" icon="fa fa-cog" outcome="/admin/tipoDocumento/listado"/>
                <p:separator/>
                <p:menuitem id="rm_admin_usuario" value="Usuarios" icon="fa fa-cog" outcome="/admin/usuario/listado"/>
            </p:submenu>


        </pv:menu>
    </h:form>

</ui:composition>

web/WEB-INF/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
            <meta name="apple-mobile-web-app-capable" content="yes" />
        </f:facet>
        <title>Grupo Cartes - Curriculums</title>

        <h:outputScript name="js/layout.js" library="volt-layout" />

        <ui:insert name="head" />
    </h:head>

    <h:body styleClass="BlueBody PopupMenu">

        <ui:include src="topbar.xhtml" />

        <div id="layout-portlets-cover">
            <div id="layout-portlets-cover-indent">
                <div id="layout-portlets-table">

                    <div id="layout-portlets-tablerow">

                        <div id="layout-portlets-tablecell-left">
                            <div id="layout-menu-cover">
                                
                                <ui:include src="layoutmenu.xhtml" />
                            </div>
                        </div>
                        <div id="layout-portlets-tablecell-right">
                            <ui:insert name="content">
                                Template
                            </ui:insert>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="Container100 TexAlCenter White Fs14 FontVoltLight Opac60">
            <div class="EmptyBox30"></div>
            @Copyright Tabacos del Paraguay S.A. All rights reserved.
            <div class="EmptyBox30"></div>
        </div>

        <h:outputStylesheet name="css/core-layout.css" library="volt-layout" />
        <h:outputStylesheet name="css/animate.css" library="volt-layout" />
        <h:outputStylesheet name="css/volt-font.css" library="volt-layout" />
        <h:outputStylesheet name="css/font-awesome.css" library="volt-layout" />
        <h:outputStylesheet name="css/volt-layout.css" library="volt-layout" />
        <h:outputStylesheet name="main.css" library="css" />
    </h:body>

</html>

web/WEB-INF/template2.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
            <meta name="apple-mobile-web-app-capable" content="yes" />
        </f:facet>
        <title>Grupo Cartes - Curriculums</title>


        <h:outputScript name="js/layout.js" library="volt-layout" />

        <ui:insert name="head" />
    </h:head>

    <h:body styleClass="PopupMenu" style="background-color: #eeeeee">

        <ui:include src="topbar2.xhtml" />

        <div id="layout-portlets-cover">
            <div id="layout-portlets-cover-indent">
                <div id="layout-portlets-table">

                    <div id="layout-portlets-tablerow">

                        <div id="layout-portlets-tablecell-left">
                            <div id="layout-menu-cover">


                            </div>
                        </div>
                        <div id="layout-portlets-tablecell-right">
                            <ui:insert name="content">
                                Template
                            </ui:insert>
                        </div>
                    </div>


                </div>



            </div>
        </div>



        <div class="Container100 TexAlCenter Fs14 FontVoltLight Opac60" style="color: #222222">
            <div class="NoIndent">
                <div style="width: 90%;
                     height: auto;
                     padding: 80px 5% 20px;
                     margin: 0px auto;
                     overflow: hidden;" class="TexAlCenter">

                </div>





                <a href="http://www.lanacion.com.py/" style="margin-right: 20px"><p:graphicImage library="img" name="logo_lanacion.png" height="50"/></a>







                <a href="http://www.radiomontecarlo.com.py/100.9/" style="margin-right: 20px"><p:graphicImage library="img" name="logo_montecarlo.png" height="50"/></a>






                <a href="http://www.radio970am.com.py/" style="margin-right: 10px"><p:graphicImage library="img" name="logo_radio_970.png" height="50"/></a>





                <a href="http://www.cronica.com.py/"><p:graphicImage library="img" name="logo_cronica.png" height="50"/></a>











            </div>

        </div>





        <div class="Container100 TexAlCenter Fs14 FontVoltLight Opac60" style="color: #222222">
            <div class="EmptyBox30"></div>
            @Copyright Tabacos del Paraguay S.A. All rights reserved.
            <div class="EmptyBox30"></div>
        </div>

        <h:outputStylesheet name="css/core-layout.css" library="volt-layout" />
        <h:outputStylesheet name="css/animate.css" library="volt-layout" />
        <h:outputStylesheet name="css/volt-font.css" library="volt-layout" />
        <h:outputStylesheet name="css/font-awesome.css" library="volt-layout" />
        <h:outputStylesheet name="css/volt-layout.css" library="volt-layout" />
        <h:outputStylesheet name="main.css" library="css" />
    </h:body>

</html>

web/WEB-INF/topbar.xhtml
<ui:composition 

    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">


    <!-- TOPBAR START -->    
    <div id="layout-topbar">
        <div id="layout-topbar-indent">
            <a id="menu-button"><i class="icon-th-menu"></i></a>

            <a href="#{request.contextPath}/main/curriculo/listado.xhtml" style="position: relative; left: 20px; top: 5px"><p:graphicImage library="img" name="logo.png" height="50"/></a>

            <span class="DispInlBlock Fright" style="margin:10px 10px 0px 0px;">
                <h:form styleClass="DispInline">
                    <p:splitButton value="Mi cuenta" icon="fa fa-user" styleClass="White Fs14" appendTo="@this">
                        <p:menuitem value="Cambiar clave" icon="fa fa-key" outcome="/admin/usuario/cambiarClave"/>
                        <p:menuitem value="Salir" icon="fa fa-power-off" action="#{autenticador.logout()}"/>
                    </p:splitButton>
                </h:form>
            </span>
        </div>
    </div>
    <!-- TOPBAR END -->

    <!-- TOPMENU START -->
    <ul id="top-menu">
        <li style="float:left; border:none;">
            <a href="#">
                <i class="icon-vcard Opac80 Fs28"></i><span><span class="Fs16">Bienvenido/a, #{credencial.usuario.nombres}</span></span>
            </a>
        </li>

        <li>
            <a href="#{request.contextPath}/main/curriculo/listado.xhtml?estado=3"><i class="icon-archive Opac80"></i><span><span class="Fs16">Contratos</span> <br/> <span class="Opac50 Fs12">#{curriculoBean.countContratado} curriculums</span></span></a>
        </li>

        <li>
            <a href="#{request.contextPath}/main/curriculo/listado.xhtml?estado=2"><i class="icon-paperclip Opac80"></i><span><span class="Fs16">Pre selecionados</span> <br/> <span class="Opac50 Fs12">#{curriculoBean.countPreseleccionado} curriculums</span></span></a>
        </li>
        <li>
            <a href="#{request.contextPath}/main/curriculo/listado.xhtml?estado=1"><i class="icon-plus Opac80"></i><span><span class="Fs16">Nuevos</span> <br/> <span class="Opac50 Fs12">#{curriculoBean.countNuevos} curriculums</span></span></a>
        </li>

    </ul>
    <!-- TOPMENU END -->

</ui:composition>

web/WEB-INF/topbar2.xhtml
<ui:composition 

    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">


    <!-- TOPBAR START -->    
    <div id="layout-topbar">
        <div id="layout-topbar-indent" style="background-color: #2D6C8D!important; border-color: #2D6C8D!important;">

            <div class="TexAlCenter">
                <span class="DispInlBlock" style="margin:10px 10px 0px 0px; color: white">
                    <i class="fa fa-smile-o Opac80 Fs28" style="margin-right: 10px"></i><span><span class="Fs16">Bienvenido/a, ¿quieres trabajar con nosotros?. Llena este formulario con tus datos y adjunta tu curriculum!</span></span>
                </span>
            </div>

        </div>
    </div>
    <!-- TOPBAR END -->

    <!-- TOPMENU START -->

    <div style="width: 90%; margin: 0 auto;">


        <div style="width: 90%;
             height: auto;
             padding: 80px 5% 20px;
             margin: 0px auto;
             overflow: hidden;" class="TexAlCenter">
            <a href="http://www.lanacion.com.py/"><p:graphicImage library="img" name="logo.png" height="150"/></a>
        </div>

    </div>


    <!-- TOPMENU END -->

</ui:composition>